### ISSUE TITLE
Stabalized Aim Charm

### ISSUE THREAD

**Issue by MugmanLord** [TTacco/Hollow-Point#10]
The moment I equip it, when I am on the ground and fire bullets they don't even get out of my gun, no damage no projectile, consumes souls anyway. I thought I had some issue with something else or that it was an old version of the mod but I have the 1.0.0.0 Version. When I remove it, projectiles are normal, the moment I equip this Charm nothing works anymore on the ground. My projectiles only works when I am in mid-air with this Charm.

**Comment by TTacco** [comment]
Yup noted already, it worked by reducing heat/deviation directly which means at 0 heat/recoil, it goes to negative which causes your bullets to not exist, for some reason

Fixed it in my current build now which checks and prevents heat from going below 0

**Comment by MugmanLord** [comment]
Recently I have combined infinite notches and Hollow point mods. At some point I bugged and was half the time invincible, couldnt kill the boss, switch weapon etc. I quit the game the save was corrupted. Its either the fact I had too much charms or the fact that I recently added the 3 charms that were companions togheter. Doing a backup should be probably recommended with the mix of those two mods.

**Comment by TTacco** [comment]
Hmmm, i havent tested it in a lot mods for compatibility but ill try to take a look into this sometime in the future before i fully release it, thanks for the heads up

**Comment by scottboyd-ai** [comment]
This is still not working on the master branch.

**Comment by TTacco** [comment]
No longer an issue because the charm has now been repurposed entirely in the 1.0 release
