### ISSUE TITLE
Sound effects not modified by game options

### ISSUE THREAD

**Issue by Thrupney** [TTacco/Hollow-Point#14]
Heyo! Love the mod!

The gunshots and equipping SFX are not modified by in-game audio options. Even with all sliders at 0% (master, SFX, music), the mod's SFX are still at full volume.

Thanks!

**Comment by TTacco** [comment]
Fixed on my current, non downloadable build

Still redoing charms atm

**Comment by TTacco** [comment]
Sounds are now affected by in game options (TY SFGrenade)
