### ISSUE TITLE
Grenade launch activates in inventory menu

### ISSUE THREAD

**Issue by TherminatorX** [TTacco/Hollow-Point#15]
Version 1.0.0.0

Enter the menu while the rifle is out, quick cast button still activates the grenade.
Particularly bothersome when using controller as I do since quick cast is the same button as switch menu right.

**Comment by TherminatorX** [comment]
Note: peforming this causes other actions to be done from the inventory menu as well such as jumping and movement.

**Comment by TTacco** [comment]
Huh, interesting

First time ive heard that happen, will look into it thanks

**Comment by TTacco** [comment]
Grenade mechanic was changed into something else in 1.0 and is no longer applicable.
