### ISSUE TITLE
Won't Work

### ISSUE THREAD

**Issue by TumboThe31st** [TTacco/Hollow-Point#17]
I have tried everything and i do have mod common but for some reason when i enter a game it just doesn't work, its just normal hollow knight, please respond ASAP

**Comment by TTacco** [comment]
Did you use the installer? it only requires both mod common and the API, and make sure the mods appear on your top left corner to ensure it works.

**Comment by TumboThe31st** [comment]
Yea i have everything i need for it but upon loading the game, it just doesn’t work

**Comment by TTacco** [comment]
Most likely API or ModCommon related.
