### ISSUE TITLE
Game halting problem with update

### ISSUE THREAD

**Issue by MherosS** [TTacco/Hollow-Point#20]
With the new adrenaline system, it removes charge healing. Which is fine, its interesting, may need some tweaks, however that is not inherently the problem.

There are a handful of times in the game where charging is required to progress in the game. Most notably, when your trying to kill the keepers.
As it stands now with the mod, you hit the keeper and when it asks you to charge to absorb them....you cant, You have no way to perform the action, requiring you to quit, uninstall the mod, go back into the game, kill the keeper, absorb it, then quit and reinstall mod to keep using the mod.

It's just a very unfortunate by product of removing the charge

**Comment by TTacco** [comment]
Should be fixed now, I reintroduced focusing to allow you to "reload" your gun at the cost of adrenaline instead of straight out disabling it.
