### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by Dodgy12354** [TTacco/Hollow-Point#21]
When I followed the steps to install Hollow Point, it installed Hollow Point (Beta) and I couldn't fire the gun.  Please help me understand how to correctly install the mod.

**Comment by TTacco** [comment]
Next time please redirect questions like this to the official Discord #modding-help channel, thats where most of the installation related questions are answered regardless of any mods.

As for your question its most likely related to not install ModCommon, ive already placed it as a requirement in the README.
