### ISSUE TITLE
Literally not functioning

### ISSUE THREAD

**Issue by Slappy-the-Lad** [TTacco/Hollow-Point#26]
I have a gun and I can shoot it but no bullets come out. After I shoot I can't shoot for a bit before the process repeats it self. This happens when I'm at full soul. Can't damage anything in kings pass.

**Comment by RedFrog6002** [comment]
Did this happen after creating a new save?

**Comment by Slappy-the-Lad** [comment]
Yes

**Comment by RedFrog6002** [comment]
Read the readme. It explains that the mod glitches on creating a new save and how to get around that
