### ISSUE TITLE
Baldur Shell (Blast Shell) hurts player for 2 masks and doesn't launch

### ISSUE THREAD

**Issue by TheDarkestShado1** [TTacco/Hollow-Point#8]
Tested with only gathering swarm and blast shell and it wouldn't work. Also tested with only blast shell and it does the same.

Using the latest version on the mod launcher.

**Comment by TTacco** [comment]
Fixed in the current build (not the on in the installer), it was probably because of the explosions double hitting and the checks are failing for it, 56 removing those checks fixed it.

**Comment by TTacco** [comment]
Rocket Jump removed due to super niche used compared to boosting, rendered obsolete and removed.

Baldur should correctly protect the player now.
